# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-48fe6880-b49f-4c45-9ef6-d1d4584578b7";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-48fe6880-b49f-4c45-9ef6-d1d4584578b7".device = "/dev/disk/by-uuid/48fe6880-b49f-4c45-9ef6-d1d4584578b7";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-48fe6880-b49f-4c45-9ef6-d1d4584578b7";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-48fe6880-b49f-4c45-9ef6-d1d4584578b7";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1619-433B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-60e53d91-b168-4524-b458-fae12dc78386"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
